# v0: xyz, v1: ZEGGS by yongkang, v1: ZEGGS by yongkang bugfix

h5file: "../process/speaker_2_10"   # "../process/speaker_2_10_v0.h5"
n_poses: 150
motion_resampling_framerate: 30     # 20 -> 60
motion_dim: 684     # 684/1141
njoints: 2052    # 684 * 3 = 2052
latent_dim: 384   # 256 -> 512, 384
n_seed: 30
cond_mask_prob: 0.1
style_dim: 2
audio_feature_dim: 1434   # 1133 + 301; audio_f + text_f
audio_feat_dim_latent: 96   # 64 -> 128, 96
num_workers: 4 
batch_size: 350
log_interval: 50
weight_decay: 0.0
lr_anneal_steps: 0
save_dir: "./BEAT_mymodel4_512"
audio_feat: "wavlm"
max_num_steps: 50000000
save_iters: 180000
name: "DiffuseStyleGesture+"   # "DiffuseStyleGesture", "DiffuseStyleGesture+", "DiffuseStyleGesture++"
version: "v0"   # "v0, v1"
suffix: ""

lr: 0.00003     # 0.00003 ->
betas: [0.5, 0.999]
milestones: [100, 200]
gamma: 0.1

