
# ZEGGS
train_data_path: "../../ubisoft-laforge-ZeroEGGS-main/data/processed_v1/processed/train/train_lmdb/train_lmdb/"     # speaker_1_state_0
val_data_path: "../../ubisoft-laforge-ZeroEGGS-main/data/processed_v1/processed/valid/valid_lmdb/valid_lmdb/"

# 60 fps + normalized
data_mean: "../../ubisoft-laforge-ZeroEGGS-main/data/processed_v1/processed/mean.npz"
data_std: "../../ubisoft-laforge-ZeroEGGS-main/data/processed_v1/processed/std.npz"

n_poses: 88     # 88 -> 20*60
n_codes: 30
motion_resampling_framerate: 20     # 20 -> 60
subdivision_stride: 10      # 10 -> 200
batch_size: 300       # 384 -> 32
loader_workers: 2
epochs: 500     # 500 -> 10
save_per_epochs: 25     # 20 -> 1
model_save_path: "./output/train_DiffuseStyleGesture"
name: "DiffuseStyleGesture"
log_interval: 50
weight_decay: 0.0
lr_anneal_steps: 0
save_dir: "./zeggs_mymodel3_wavlm"
audio_feat: "wavlm"     # wav encoder; mfcc; wavlm

lr: 0.00003     # 0.00003 ->
betas: [0.5, 0.999]
milestones: [100, 200]
gamma: 0.1

